// [B27.4] 50 обезличенных подсказок-вопросов для empty-состояния ассистента.
// Контент-данные, НЕ i18n-словарь (150 ключей сломали бы DotPath-тип
// TranslationKey). Локали синхронизированы типом; выборка — случайные
// SUGGEST_COUNT на маунт (частичный Fisher-Yates, rand инжектируется в тестах).

import type { Locale } from '../../i18n';

export const SUGGEST_COUNT = 4;

export const SUGGESTIONS: Record<Locale, readonly string[]> = {
  ru: [
    'О чём был последний звонок?',
    'Какие задачи назначили на этой неделе?',
    'Что решили по срокам?',
    'Какие риски обсуждали?',
    'Что обсуждали вчера?',
    'Какие решения приняли на последней встрече?',
    'Что обещали клиенту?',
    'Какие вопросы остались открытыми?',
    'Что говорили про бюджет?',
    'Когда обсуждали интеграцию?',
    'Какие дедлайны называли?',
    'Что решили по продукту?',
    'Какие проблемы поднимали на этой неделе?',
    'О чём договорились в итоге?',
    'Что обсуждали в прошлом месяце?',
    'Какие следующие шаги назвали?',
    'Что говорили про цену?',
    'Какие возражения звучали?',
    'Что решили по дизайну?',
    'Когда говорили про запуск?',
    'Какие метрики обсуждали?',
    'Что говорили о конкурентах?',
    'Какие договорённости по оплате?',
    'Что просили исправить?',
    'Какие фичи запрашивали?',
    'Что говорили про команду?',
    'Какие сроки сдвигали?',
    'О чём спорили на встрече?',
    'Что решили отложить?',
    'Какие требования озвучили?',
    'Что говорили про документацию?',
    'Какие блокеры называли?',
    'Что обсуждали про найм?',
    'Какие итоги демо?',
    'Что говорили про безопасность?',
    'Какие правки согласовали?',
    'Что обещали прислать?',
    'Когда планировали следующую встречу?',
    'Какие цели ставили на квартал?',
    'Что говорили про поддержку?',
    'Какие условия контракта обсуждали?',
    'Что решили по тестированию?',
    'Какие идеи предлагали?',
    'Что говорили про производительность?',
    'Какие вопросы задавал клиент?',
    'Что обсуждали про партнёрство?',
    'Какие замечания были к отчёту?',
    'Что решили по релизу?',
    'Какие приоритеты назвали?',
    'Что говорили про обучение?',
  ],
  en: [
    'What was the last call about?',
    'What tasks were assigned this week?',
    'What was decided about deadlines?',
    'What risks were discussed?',
    'What was discussed yesterday?',
    'What decisions came out of the last meeting?',
    'What was promised to the client?',
    'Which questions are still open?',
    'What was said about the budget?',
    'When was the integration discussed?',
    'What deadlines were mentioned?',
    'What was decided about the product?',
    'What problems came up this week?',
    'What was finally agreed on?',
    'What was discussed last month?',
    'What next steps were named?',
    'What was said about pricing?',
    'What objections came up?',
    'What was decided about the design?',
    'When was the launch discussed?',
    'What metrics were discussed?',
    'What was said about competitors?',
    'What payment agreements were made?',
    'What was asked to be fixed?',
    'What features were requested?',
    'What was said about the team?',
    'Which deadlines were moved?',
    'What was argued about in the meeting?',
    'What was postponed?',
    'What requirements were voiced?',
    'What was said about documentation?',
    'What blockers were named?',
    'What was discussed about hiring?',
    'What were the demo takeaways?',
    'What was said about security?',
    'What edits were approved?',
    'What was promised to be sent?',
    'When was the next meeting planned?',
    'What goals were set for the quarter?',
    'What was said about support?',
    'What contract terms were discussed?',
    'What was decided about testing?',
    'What ideas were proposed?',
    'What was said about performance?',
    'What questions did the client ask?',
    'What was discussed about partnership?',
    'What remarks were made on the report?',
    'What was decided about the release?',
    'What priorities were named?',
    'What was said about training?',
  ],
  kk: [
    'Соңғы қоңырау не туралы болды?',
    'Осы аптада қандай тапсырмалар берілді?',
    'Мерзімдер бойынша не шешілді?',
    'Қандай тәуекелдер талқыланды?',
    'Кеше не талқыланды?',
    'Соңғы кездесуде қандай шешімдер қабылданды?',
    'Клиентке не уәде етілді?',
    'Қандай сұрақтар ашық қалды?',
    'Бюджет туралы не айтылды?',
    'Интеграция қашан талқыланды?',
    'Қандай мерзімдер аталды?',
    'Өнім бойынша не шешілді?',
    'Осы аптада қандай мәселелер көтерілді?',
    'Қорытындыда не келісілді?',
    'Өткен айда не талқыланды?',
    'Қандай келесі қадамдар аталды?',
    'Баға туралы не айтылды?',
    'Қандай қарсылықтар айтылды?',
    'Дизайн бойынша не шешілді?',
    'Іске қосу қашан талқыланды?',
    'Қандай метрикалар талқыланды?',
    'Бәсекелестер туралы не айтылды?',
    'Төлем бойынша қандай уағдаластықтар болды?',
    'Нені түзетуді сұрады?',
    'Қандай функциялар сұралды?',
    'Команда туралы не айтылды?',
    'Қандай мерзімдер жылжытылды?',
    'Кездесуде не туралы пікірталас болды?',
    'Нені кейінге қалдыруды шешті?',
    'Қандай талаптар айтылды?',
    'Құжаттама туралы не айтылды?',
    'Қандай кедергілер аталды?',
    'Жалдау туралы не талқыланды?',
    'Демоның қорытындылары қандай?',
    'Қауіпсіздік туралы не айтылды?',
    'Қандай түзетулер келісілді?',
    'Нені жіберуге уәде берді?',
    'Келесі кездесу қашан жоспарланды?',
    'Тоқсанға қандай мақсаттар қойылды?',
    'Қолдау туралы не айтылды?',
    'Келісімшарттың қандай шарттары талқыланды?',
    'Тестілеу бойынша не шешілді?',
    'Қандай идеялар ұсынылды?',
    'Өнімділік туралы не айтылды?',
    'Клиент қандай сұрақтар қойды?',
    'Серіктестік туралы не талқыланды?',
    'Есепке қандай ескертулер болды?',
    'Релиз бойынша не шешілді?',
    'Қандай басымдықтар аталды?',
    'Оқыту туралы не айтылды?',
  ],
};

/** Частичный Fisher-Yates: первые n позиций перемешанной копии. */
export function pickSuggestions(
  pool: readonly string[],
  n: number = SUGGEST_COUNT,
  rand: () => number = Math.random,
): string[] {
  const arr = [...pool];
  const count = Math.min(n, arr.length);
  for (let i = 0; i < count; i += 1) {
    const j = i + Math.floor(rand() * (arr.length - i));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count);
}
