#!/usr/bin/env bash
# scripts/refresh-model-catalog.sh
#
# Wotold M12 — обновление каталога моделей.
# Запускается раз при настройке M12.4 и каждый раз когда апгрейдим версии моделей.
# Выводит готовый блок Rust-кода для вставки в local_engine/models.rs.
#
# ⚠️  SECURITY (Review M-4):
#
# Скрипт доверяет SHA256 от HuggingFace CDN (через X-Linked-Etag header или
# paths-info API). Если HF когда-либо compromised, выданный hash может быть
# attacker-controlled — потом он pinin'ится в MODEL_CATALOG и все юзеры
# скачают «правильный по нашей точке зрения» файл. Bootstrap integrity gap.
#
# Mitigation: перед commit обновлённого `MODEL_CATALOG`:
#   1. Запустить скрипт с разных машин / IP / VPN → сравнить выводы.
#   2. Cross-check каждой SHA256 против upstream-публикованных checksums:
#      - whisper.cpp: https://huggingface.co/ggerganov/whisper.cpp →
#        files page показывает SHA в File info → Etag column.
#      - bartowski/Qwen*: проверить против commit hashes в `model card`
#        или скачать локально и `shasum -a 256`.
#   3. Refresh не запускать на CI/build-машинах автоматически — только
#      ручной dev-flow с явным diff review.
#
# Чтобы случайно не запустить — установить WOTOLD_CATALOG_REFRESH_CONFIRMED=1.
#
# Использование:
#   WOTOLD_CATALOG_REFRESH_CONFIRMED=1 ./scripts/refresh-model-catalog.sh           # stdout
#   WOTOLD_CATALOG_REFRESH_CONFIRMED=1 ./scripts/refresh-model-catalog.sh > out.rs  # в файл
#
# Зависимости: curl, jq

# `set -e` без `pipefail`: pipefail ломает grep|tail|sed-цепочку когда grep
# не находит match (1 → exit), а это нормальная ситуация (используем fallback
# на paths-info API). Каждая критичная команда оборачивается в `|| true`.
set -eu

# [Security] Guard от случайного запуска. См. блок ⚠️  SECURITY выше.
if [[ "${WOTOLD_CATALOG_REFRESH_CONFIRMED:-0}" != "1" ]]; then
  cat >&2 <<'EOF'
⚠️  refresh-model-catalog.sh обновляет SHA256 pins в MODEL_CATALOG из
   HuggingFace CDN. Скрипт ДОВЕРЯЕТ ответам HF. Перед запуском прочитайте
   блок ⚠️  SECURITY в начале скрипта (cross-check workflow).

   Когда готовы — установите ENV и перезапустите:
     WOTOLD_CATALOG_REFRESH_CONFIRMED=1 ./scripts/refresh-model-catalog.sh
EOF
  exit 2
fi

# Каталог моделей. Формат: id|repo|file
#
# Notes:
# - `whisper-small` хранится у ggerganov только в Q5_1 квантизации
#   (для medium/large-v3 есть Q5_0 — историческая разница в датах публикации).
# - **Gemma 3 2B заменён на Qwen 2.5 1.5B** для Light preset: репы
#   bartowski/gemma-3-2b-it-GGUF, unsloth/gemma-3-2b-it-GGUF,
#   google/gemma-2-2b-it возвращают 401 / "Access is restricted" — Google TOS
#   gating без HF token. PRD §11 O1 разрешает замену LLM («не финал, дверь
#   открыта»). Qwen 1.5B имеет приличный русский и не требует accept-license
#   flow на стороне юзера. Если позже захотим Gemma — нужен HF_TOKEN в
#   скрипте + UI-шаг «принять Gemma TOS» в onboarding (deferred).
MODELS=(
  "whisper-small|ggerganov/whisper.cpp|ggml-small-q5_1.bin"
  "whisper-medium|ggerganov/whisper.cpp|ggml-medium-q5_0.bin"
  "whisper-large-v3|ggerganov/whisper.cpp|ggml-large-v3-q5_0.bin"
  "qwen25-1_5b|bartowski/Qwen2.5-1.5B-Instruct-GGUF|Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"
  "qwen25-3b|bartowski/Qwen2.5-3B-Instruct-GGUF|Qwen2.5-3B-Instruct-Q4_K_M.gguf"
  "qwen25-7b|bartowski/Qwen2.5-7B-Instruct-GGUF|Qwen2.5-7B-Instruct-Q4_K_M.gguf"
  # [M12-D5] Speaker diarization (sherpa-onnx OfflineSpeakerDiarization).
  # pyannote segmentation — single model.onnx ~6 MB на HF mirror.
  # WeSpeaker embedding — reuse `voice_model.rs` (B3.7c) ~26 MB, не в этом
  # каталоге; см. `voice_model::MODEL_URL` + SHA.
  "pyannote-segmentation|csukuangfj/sherpa-onnx-pyannote-segmentation-3-0|model.onnx"
  # [M15.9] Текст-эмбеддер RAG-ассистента: официальный intfloat ONNX-экспорт
  # (MIT). Имя файла упоминает avx512_vnni, но dynamic-qint8 ops исполнимы
  # и на arm64 (спайк M15.9). tokenizer.json — второй обязательный файл.
  "e5-small-qint8|intfloat/multilingual-e5-small|onnx/model_qint8_avx512_vnni.onnx"
  "e5-small-tokenizer|intfloat/multilingual-e5-small|onnx/tokenizer.json"
)

# Проверка зависимостей
for cmd in curl jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "error: '$cmd' не установлен" >&2
    exit 1
  fi
done

echo "// Auto-generated by scripts/refresh-model-catalog.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "// DO NOT edit by hand — run the script to regenerate."
echo "// To bump a model version: edit MODELS in the script, re-run."
echo
echo "pub static MODEL_CATALOG: &[ModelEntry] = &["

for line in "${MODELS[@]}"; do
  IFS='|' read -r id repo file <<< "$line"
  url="https://huggingface.co/${repo}/resolve/main/${file}"

  # HEAD-запрос даёт X-Linked-Etag (SHA256 для LFS) и Content-Length
  headers=$(curl -sIL "$url" 2>/dev/null || true)

  sha=$(echo "$headers" | grep -i '^x-linked-etag:' | tail -1 | sed 's/.*"\(.*\)".*/\1/' | tr -d '\r')
  size=$(echo "$headers" | grep -i '^content-length:' | tail -1 | awk '{print $2}' | tr -d '\r')

  # Fallback на paths-info API если HEAD не дал SHA (бывает для не-LFS файлов)
  if [[ -z "$sha" ]]; then
    api_resp=$(curl -s -X POST "https://huggingface.co/api/models/${repo}/paths-info/main" \
      -H "Content-Type: application/json" \
      -d "{\"paths\":[\"${file}\"]}" 2>/dev/null || echo "[]")
    sha=$(echo "$api_resp" | jq -r '.[0].lfs.oid // empty')
    size=$(echo "$api_resp" | jq -r '.[0].size // empty')
  fi

  if [[ -z "$sha" || -z "$size" ]]; then
    echo "    // ERROR: не удалось получить SHA/size для $id ($repo/$file)" >&2
    echo "    //        проверь имя файла на https://huggingface.co/$repo/tree/main" >&2
    continue
  fi

  # Определяем kind по id
  case "$id" in
    whisper-*)        kind="ModelKind::Stt" ;;
    pyannote-*)       kind="ModelKind::Diarization" ;;
    e5-*)             kind="ModelKind::Embedding" ;;
    *)                kind="ModelKind::Llm" ;;
  esac

  # Human-readable display name
  case "$id" in
    whisper-small)         display="Whisper Small (RU+EN)" ;;
    whisper-medium)        display="Whisper Medium (RU+EN)" ;;
    whisper-large-v3)      display="Whisper Large v3" ;;
    qwen25-1_5b)           display="Qwen 2.5 (1.5B)" ;;
    qwen25-3b)             display="Qwen 2.5 (3B)" ;;
    qwen25-7b)             display="Qwen 2.5 (7B)" ;;
    pyannote-segmentation) display="Pyannote Segmentation 3.0" ;;
    e5-small-qint8)        display="Multilingual E5 Small (поиск)" ;;
    e5-small-tokenizer)    display="Multilingual E5 Tokenizer" ;;
    *)                     display="$id" ;;
  esac

  cat <<EOF
    ModelEntry {
        id:           "$id",
        kind:         $kind,
        display_name: "$display",
        url:          "$url",
        sha256:       "$sha",
        size_bytes:   $size,
        license_url:  "https://huggingface.co/${repo}",
    },
EOF

done

echo "];"
