#!/usr/bin/env bash
# scripts/refresh-model-catalog.sh
#
# Wotold M12 — обновление каталога моделей.
# Запускается раз при настройке M12.4 и каждый раз когда апгрейдим версии моделей.
# Выводит готовый блок Rust-кода для вставки в local_engine/models.rs.
#
# Использование:
#   ./scripts/refresh-model-catalog.sh           # выводит в stdout
#   ./scripts/refresh-model-catalog.sh > out.rs  # в файл
#
# Зависимости: curl, jq

# `set -e` без `pipefail`: pipefail ломает grep|tail|sed-цепочку когда grep
# не находит match (1 → exit), а это нормальная ситуация (используем fallback
# на paths-info API). Каждая критичная команда оборачивается в `|| true`.
set -eu

# Каталог моделей. Формат: id|repo|file
#
# Notes:
# - `whisper-small` хранится у ggerganov только в Q5_1 квантизации
#   (для medium/large-v3 есть Q5_0 — историческая разница в датах публикации).
# - **Gemma 3 2B заменён на Qwen 2.5 1.5B** для Light preset: репы
#   bartowski/gemma-3-2b-it-GGUF, unsloth/gemma-3-2b-it-GGUF,
#   google/gemma-2-2b-it возвращают 401 / "Access is restricted" — Google TOS
#   gating без HF token. PRD §11 O1 разрешает замену LLM («не финал, дверь
#   открыта»). Qwen 1.5B имеет приличный русский и не требует accept-license
#   flow на стороне юзера. Если позже захотим Gemma — нужен HF_TOKEN в
#   скрипте + UI-шаг «принять Gemma TOS» в onboarding (deferred).
MODELS=(
  "whisper-small|ggerganov/whisper.cpp|ggml-small-q5_1.bin"
  "whisper-medium|ggerganov/whisper.cpp|ggml-medium-q5_0.bin"
  "whisper-large-v3|ggerganov/whisper.cpp|ggml-large-v3-q5_0.bin"
  "qwen25-1_5b|bartowski/Qwen2.5-1.5B-Instruct-GGUF|Qwen2.5-1.5B-Instruct-Q4_K_M.gguf"
  "qwen25-3b|bartowski/Qwen2.5-3B-Instruct-GGUF|Qwen2.5-3B-Instruct-Q4_K_M.gguf"
  "qwen25-7b|bartowski/Qwen2.5-7B-Instruct-GGUF|Qwen2.5-7B-Instruct-Q4_K_M.gguf"
)

# Проверка зависимостей
for cmd in curl jq; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "error: '$cmd' не установлен" >&2
    exit 1
  fi
done

echo "// Auto-generated by scripts/refresh-model-catalog.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "// DO NOT edit by hand — run the script to regenerate."
echo "// To bump a model version: edit MODELS in the script, re-run."
echo
echo "pub static MODEL_CATALOG: &[ModelEntry] = &["

for line in "${MODELS[@]}"; do
  IFS='|' read -r id repo file <<< "$line"
  url="https://huggingface.co/${repo}/resolve/main/${file}"

  # HEAD-запрос даёт X-Linked-Etag (SHA256 для LFS) и Content-Length
  headers=$(curl -sIL "$url" 2>/dev/null || true)

  sha=$(echo "$headers" | grep -i '^x-linked-etag:' | tail -1 | sed 's/.*"\(.*\)".*/\1/' | tr -d '\r')
  size=$(echo "$headers" | grep -i '^content-length:' | tail -1 | awk '{print $2}' | tr -d '\r')

  # Fallback на paths-info API если HEAD не дал SHA (бывает для не-LFS файлов)
  if [[ -z "$sha" ]]; then
    api_resp=$(curl -s -X POST "https://huggingface.co/api/models/${repo}/paths-info/main" \
      -H "Content-Type: application/json" \
      -d "{\"paths\":[\"${file}\"]}" 2>/dev/null || echo "[]")
    sha=$(echo "$api_resp" | jq -r '.[0].lfs.oid // empty')
    size=$(echo "$api_resp" | jq -r '.[0].size // empty')
  fi

  if [[ -z "$sha" || -z "$size" ]]; then
    echo "    // ERROR: не удалось получить SHA/size для $id ($repo/$file)" >&2
    echo "    //        проверь имя файла на https://huggingface.co/$repo/tree/main" >&2
    continue
  fi

  # Определяем kind по id
  if [[ "$id" == whisper-* ]]; then
    kind="ModelKind::Stt"
  else
    kind="ModelKind::Llm"
  fi

  # Human-readable display name
  case "$id" in
    whisper-small)    display="Whisper Small (RU+EN)" ;;
    whisper-medium)   display="Whisper Medium (RU+EN)" ;;
    whisper-large-v3) display="Whisper Large v3" ;;
    qwen25-1_5b)      display="Qwen 2.5 (1.5B)" ;;
    qwen25-3b)        display="Qwen 2.5 (3B)" ;;
    qwen25-7b)        display="Qwen 2.5 (7B)" ;;
    *)                display="$id" ;;
  esac

  cat <<EOF
    ModelEntry {
        id:           "$id",
        kind:         $kind,
        display_name: "$display",
        url:          "$url",
        sha256:       "$sha",
        size_bytes:   $size,
        license_url:  "https://huggingface.co/${repo}",
    },
EOF

done

echo "];"
